http_server_host = "127.0.0.1"
http_server_port = "7002"

libp2p_seed = 3
libp2p_port = "37002"
ipfs_path = "avail_ipfs_store_3"

# put full_node_rpc = https://testnet.polygonavail.net/rpc incase you are connecting to devnet
full_node_rpc = ["http://127.0.0.1:9933"]
# put full_node_ws = wss://testnet.polygonavail.net/ws incase you are connecting to devnet
full_node_ws = ["ws://127.0.0.1:9944"]
# None in case of default Light Client Mode
app_id = 1

confidence = 92.0
avail_path = "avail_path_3"
prometheus_port = 9522
sync_blocks_depth=200
block_matrix_partition = "2/20"
bootstraps = [["12D3KooWStAKPADXqJ7cngPYXd2mSANpdgh1xQ34aouufHA2xShz","/ip4/127.0.0.1/tcp/37000"]]
# See https://docs.rs/log/0.4.14/log/enum.LevelFilter.html for possible log level values
log_level = "INFO"
