log_level = "info"
http_server_host = "127.0.0.1"
http_server_port = "7001"

ipfs_seed = 2
ipfs_port = "37001"
ipfs_path = "avail_ipfs_store_1"

full_node_rpc = ["http://127.0.0.1:9933"]
full_node_ws = ["ws://127.0.0.1:9944"]
app_id = 1
confidence = 92.0
avail_path = "avail_path_!"
prometheus_port = 9520
bootstraps = []