http_server_host = '127.0.0.1'
http_server_port = '7001'
ipfs_port = '37001'
ipfs_path = 'avail_ipfs_node_2'
full_node_rpc = ['http://127.0.0.1:9933']
full_node_ws = ['ws://127.0.0.1:9944']
confidence = 92.0
bootstraps = []
avail_path = 'avail_light_client_2'
log_level = 'INFO'
log_format_json = false
prometheus_port = 9520
disable_rpc = false
disable_proof_verification = false
disable_client_sync = false
max_parallel_fetch_tasks = 8
